version: '3'
services:
  mysrv:
    container_name: backend
    image: backend-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:3000
    restart: always
  db:
    container_name: database
    image: postgres:13
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw
  web:
    container_name: frontend
    image: nginx
    restart: always
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 8081:80
  caddy:
    container_name: ssl
    image: caddy:2-alpine
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 80:80
      - 443:443
